### ISSUE TITLE
Missing license for source files

### ISSUE THREAD

**Issue by kekec** [misaz/BGT60LTR11-Library#1]
Hi Misaz,

great job creating this library. You might want to added licensing information to you repo plus individual source files.

Thank you!
Paul

**Comment by misaz** [comment]
Thank you for feedback. License is MIT. I added it to files in [5d32337](https://github.com/misaz/BGT60LTR11-Library/commit/5d32337b9788d5a8d1f555cdc884f2bd76ed632e)
